name: Clang-Tidy nightly check

on:
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * *" # run at 4 AM JST

jobs:
  build-using-clang:
    runs-on: ubuntu-latest
    container: ubuntu:focal

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@v0.1
        with:
          required-ros-distributions: foxy

      - name: Install Clang-Tidy
        run: |
          apt-get update -q
          apt-get install -y clang-tidy-11
          update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-11 9999

      - name: Clone dependency packages
        run: |
          mkdir dependency_ws
          vcs import dependency_ws < build_depends.repos

      - name: Install missing dependencies
        run: |
          rosdep update
          DEBIAN_FRONTEND=noninteractive rosdep install --from-paths . --ignore-src --rosdistro foxy -y
          apt-get install -y \
            ros-foxy-tf2>=0.13.6-1focal.20201028.172335 \
            ros-foxy-tf2-geometry-msgs>=0.13.6-1focal.20201028.172335 \
            ros-foxy-tf2-ros>=0.13.6-1focal.20201028.172335 \
            ros-foxy-tf2-sensor-msgs>=0.13.6-1focal.20201028.172335

      - name: Build
        run: |
          . /opt/ros/foxy/setup.sh
          colcon build --event-handlers console_cohesion+ \
                      --continue-on-error \
                      --cmake-args \
                        -DCMAKE_BUILD_TYPE=Release \
                        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
                        -DFORCE_BUILD_VENDOR_PKG=ON

      - name: Checkout CodeChecker
        uses: actions/checkout@v2
        with:
          repository: "Ericsson/codechecker"
          path: "codechecker"
          fetch-depth: "1"

      - name: Install CodeChecker
        continue-on-error: true
        # General Instruction https://github.com/Ericsson/codechecker#linux
        run: |
          apt-get install gcc-multilib python3-venv -y
          cd codechecker

          # Got 'bdist_wheel' error? No problem.
          # See https://github.com/Ericsson/codechecker/issues/3108#issuecomment-748120874
          make venv || true
          . "${PWD}/venv/bin/activate"
          BUILD_UI_DIST=NO make package || true

      - name: Debug (search for compile_commands.json)
        run: |
          ls
          echo "---"
          ls build
          echo "---"
          find . -name compile_commands.json

      - name: Analyse using Clang-Tidy
        run: |
          . "${PWD}/codechecker/venv/bin/activate"
          export PATH="${PWD}/codechecker/build/CodeChecker/bin:$PATH"
          CodeChecker analyze build/compile_commands.json --config codechecker-config.json --output ./reports
          CodeChecker parse -e html ./reports -o ./public/pr-check/main/tidy-reports --trim-path-prefix ${GITHUB_WORKSPACE}

      - name: Deploy analyse results to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: true
